### ISSUE TITLE
Discover gateways dynamically

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/backstage-tyk-entity-provider#11]
We are currently hardcoding the Gateway configurations inside tyk-catalog.yaml

```
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tyk-gateway
  title: Tyk Gateway
spec:
  type: service
  lifecycle: production
  owner: guests
  system: tyk
  providesApis:
    - tyk-gateway-api
  consumesApis:
    - default/tyk-dashboard-system-api
  dependsOn:
    - component:default/tyk-dashboard
    - resource:default/tyk-gateway-storage
```

This is really nice for describing the scenario where there is a single Gateway connected to a Dashboard, but many of our customers deploy one or more Gateways.

So in the scenario where there is a public gateway, and an internal gateway cluster, the customer would need to manually describe both gateways. Then specify which APIs each gateway provides.

- [ ] Use the Tyk Dashboard System APIs to discover connected gateways, and dynamically create Gateway components.
- [ ] Based upon connected gateway tags, populate the `providesApis` array dynamically

https://github.com/TykTechnologies/tyk-analytics/blob/2f0b1d9aecfbb5ab439385d93c0dcae42ab1dc5e/dashboard/server.go#L1199

https://github.com/TykTechnologies/tyk-analytics/blob/2f0b1d9aecfbb5ab439385d93c0dcae42ab1dc5e/dashboard/server.go#L1202
